apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynginx-rrs
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: myapp-nginx
      labels:
        app: myapp
        type: front
    spec:
      containers:
        - name: myapp-nginx
          image: nginx
  replicas: 3
  selector:
     matchLabels:
        type: front

